name: ✨Repository Creation Form
description: Request a new repository
labels: ["admin"]
title: "[REPO]: "
assignees: fredgohsman
body:
  - type: markdown
    attributes:
      value: |
        A new repository will be created if all checks are successful.
  
  - type: input
    id: name
    attributes:
      label: Repository Name
      description: The name of the repository to be created.  If a repository with the name already exists, the request will be denied.
      placeholder: repo-name
    validations:
      required: true
      
  - type: textarea
    id: description
    attributes:
      label: Repository Description
      description: A description of the repository.
      placeholder: The HR Profiles project is used ...
      
  - type: dropdown
    id: department
    attributes:
      label: Department Name
      description: Name of the department requesting the new repository.
      options:
        - HR
        - IT
        - Marketing
        - Sales
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Terms & Conditions
      description: Hereby agree to the terms and conditions set out in our policies as to the use of GitHub.
      options:
        - label: I agree
          required: true
